# Generated by Django 6.1 on 2026-09-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('word_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='word_learning.language', verbose_name='Базовыйй язык'),
        ),
    ]
