# Generated by Django 6.1 on 2026-09-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_base_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), to='account.profileicon'),
        ),
    ]
