# Generated by Django 6.1 on 2026-09-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profileicon_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileIcon',
            new_name='Avatar',
        ),
    ]
