# Generated by Django 6.1 on 2026-09-09 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_profileicon_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.avatar'),
        ),
    ]
