# Generated by Django 6.1 on 2026-09-09 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_total_xp_alter_user_icon'),
        ('word_learning', '0009_alter_topic_options_concept_position_topic_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.language')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'language'), name='unique_user_learning_language')],
            },
        ),
    ]
