# Generated by Django 6.1 on 2026-09-03 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('code', models.CharField(max_length=5, verbose_name='Код')),
                ('icon', models.FileField(upload_to='icons/archives/', verbose_name='Архив картинок для языка')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('icon', models.FileField(upload_to='icons/topics/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='words/images/', verbose_name='Картинка слова')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Концепт',
                'verbose_name_plural': 'Концепты',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('audio', models.FileField(blank=True, null=True, upload_to='words/audio/', verbose_name='Аудио')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.concept', verbose_name='Концепт')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='Profile_Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Изучен ли?')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.word', verbose_name='Слово')),
            ],
        ),
    ]
