# Generated by Django 6.1 on 2026-09-08 05:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
        migrations.AddField(
            model_name='concept',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Легко'), ('Medium', 'Средне'), ('Hard', 'Сложно')], default=2009, max_length=64, verbose_name='Сложность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concept',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='topic',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Легко'), ('Medium', 'Средне'), ('Hard', 'Сложно')], default=2009, max_length=64, verbose_name='Сложность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Транскрипция'),
        ),
        migrations.CreateModel(
            name='TopicTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.language', verbose_name='Язык')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Перевод темы',
                'verbose_name_plural': 'Переводы тем',
            },
        ),
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Кол-во правильных ответов')),
                ('wrong_answers', models.IntegerField(default=0, verbose_name='Кол-во неправильных ответов')),
                ('attempts', models.IntegerField(default=0, verbose_name='Попытки')),
                ('last_played_at', models.DateTimeField(default=datetime.datetime(2026, 9, 8, 5, 49, 14, 915488, tzinfo=datetime.timezone.utc), verbose_name='Дата последней игры')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.concept', verbose_name='Концепт')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.language', verbose_name='Язык')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Изученное слово',
                'verbose_name_plural': 'Изученные слова',
            },
        ),
        migrations.DeleteModel(
            name='Profile_Language',
        ),
    ]
