# Generated by Django 6.1 on 2026-09-08 11:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0004_wordprogress_mastery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(upload_to='achievements/icons/', verbose_name='Иконка')),
                ('condition_type', models.CharField(max_length=128, verbose_name='Условие получения')),
                ('condition_value', models.PositiveIntegerField(default=0, verbose_name='Значение условия получения')),
                ('xp_reward', models.IntegerField(default=0, verbose_name='Получаемый опыт')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.AlterField(
            model_name='profilecontentprogress',
            name='last_opened_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 8, 11, 4, 16, 138662, tzinfo=datetime.timezone.utc), verbose_name='Дата последнего открытия'),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='last_played_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 8, 11, 4, 16, 138662, tzinfo=datetime.timezone.utc), verbose_name='Дата последней игры'),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=128, verbose_name='Тип игры')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Кол-во правильных')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='Кол-во неправильных')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='Получаемый опыт')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.language', verbose_name='Язык')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровый сессии',
            },
        ),
        migrations.CreateModel(
            name='ProfileAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.achievement', verbose_name='Достижение')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Полученное достижение',
                'verbose_name_plural': 'Полученные достижения',
            },
        ),
    ]
