# Generated by Django 6.1 on 2026-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0006_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('words_learned', 'Выучено слов'), ('games_completed', 'Пройдено игр'), ('correct_answers', 'Правильных ответов'), ('perfect_games', 'Игр без ошибок'), ('poems_listened', 'Прослушано стихотворений'), ('proverbs_learned', 'Изучено пословиц'), ('topics_completed', 'Завершено тем'), ('xp_earned', 'Получено XP')], max_length=128, verbose_name='Условие получения'),
        ),
    ]
