# Generated by Django 6.1 on 2026-09-09 10:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0008_alter_achievement_xp_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AddField(
            model_name='concept',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='topic',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.ImageField(upload_to='icons/topics/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='topictranslate',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='word_learning.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='word',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='word_learning.concept', verbose_name='Концепт'),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='mastery',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Статус знания'),
        ),
        migrations.AddConstraint(
            model_name='profileachievement',
            constraint=models.UniqueConstraint(fields=('profile', 'achievement'), name='unique_profile_achievement'),
        ),
        migrations.AddConstraint(
            model_name='wordprogress',
            constraint=models.CheckConstraint(condition=models.Q(('mastery__gte', 0), ('mastery__lte', 5)), name='mastery_between_0_and_5'),
        ),
    ]
