# Generated by Django 6.1 on 2026-09-09 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0009_alter_topic_options_concept_position_topic_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Концепт', 'verbose_name_plural': 'Концепты'},
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'verbose_name': 'Игровая сессия', 'verbose_name_plural': 'Игровые сессии'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Значение условия получения'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='word_learning.topic', verbose_name='Тема'),
        ),
    ]
