# Generated by Django 6.1 on 2026-09-14 05:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0010_alter_concept_options_alter_gamesession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Количество раундов'),
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Номер раунда')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные задания')),
                ('correct_answer', models.JSONField(blank=True, default=dict, verbose_name='Правильный ответ')),
                ('submitted_answer', models.JSONField(blank=True, default=dict, verbose_name='Ответ пользователя')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Есть ответ')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Ответ полностью верный')),
                ('correct_items', models.PositiveSmallIntegerField(default=0, verbose_name='Правильных элементов')),
                ('wrong_items', models.PositiveSmallIntegerField(default=0, verbose_name='Ошибочных элементов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Отвечено')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='word_learning.concept', verbose_name='Основной концепт')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='word_learning.gamesession', verbose_name='Игровая сессия')),
            ],
            options={
                'verbose_name': 'Игровой вопрос',
                'verbose_name_plural': 'Игровые вопросы',
                'ordering': ['session_id', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('session', 'sequence'), name='unique_game_session_question_sequence')],
            },
        ),
    ]
