# Generated by Django 6.1 on 2026-09-15 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_childlearninglanguage_childprofile_subscription_and_more'),
        ('word_learning', '0011_gamesession_question_count_gamequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.childprofile', verbose_name='Профиль ребёнка'),
        ),
        migrations.AlterField(
            model_name='profileachievement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.childprofile', verbose_name='Профиль ребёнка'),
        ),
        migrations.AlterField(
            model_name='profilecontentprogress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.childprofile', verbose_name='Профиль ребёнка'),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.childprofile', verbose_name='Профиль ребёнка'),
        ),
    ]
