# Generated by Django 6.1 on 2026-09-18 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_parental_pin_hash'),
        ('word_learning', '0011_gamesession_question_count_gamequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.childprofile', verbose_name='Профиль ребёнка'),
        ),
        migrations.AlterField(
            model_name='profileachievement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.childprofile', verbose_name='Профиль ребёнка'),
        ),
        migrations.AlterField(
            model_name='profilecontentprogress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.childprofile', verbose_name='Профиль ребёнка'),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.childprofile', verbose_name='Профиль ребёнка'),
        ),
        migrations.CreateModel(
            name='DailyXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('earned_xp', models.PositiveIntegerField(default=0, verbose_name='XP за день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_xp_records', to='account.childprofile', verbose_name='Профиль ребёнка')),
            ],
            options={
                'verbose_name': 'Дневной XP',
                'verbose_name_plural': 'Дневной XP',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['profile', 'date'], name='daily_xp_profile_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'date'), name='unique_profile_daily_xp')],
            },
        ),
    ]
