# Generated by Django 6.1 on 2026-09-19 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_parental_pin_hash'),
        ('word_learning', '0012_alter_gamesession_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWordLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('required_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Слов для изучения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_word_lessons', to='word_learning.language', verbose_name='Язык')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_word_lessons', to='account.childprofile', verbose_name='Профиль ребёнка')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_word_lessons', to='word_learning.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Ежедневный урок слов',
                'verbose_name_plural': 'Ежедневные уроки слов',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyWordLessonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('listened_at', models.DateTimeField(blank=True, null=True, verbose_name='Прослушано')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_lesson_items', to='word_learning.concept', verbose_name='Концепт')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='word_learning.dailywordlesson', verbose_name='Ежедневный урок')),
            ],
            options={
                'verbose_name': 'Слово ежедневного урока',
                'verbose_name_plural': 'Слова ежедневного урока',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dailywordlesson',
            index=models.Index(fields=['profile', 'topic', 'language', 'date'], name='daily_word_lesson_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailywordlesson',
            constraint=models.UniqueConstraint(fields=('profile', 'topic', 'language', 'date'), name='unique_daily_word_lesson'),
        ),
        migrations.AddConstraint(
            model_name='dailywordlessonitem',
            constraint=models.UniqueConstraint(fields=('lesson', 'concept'), name='unique_daily_lesson_concept'),
        ),
    ]
