# Generated by Django 6.1 on 2026-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0013_dailywordlesson_dailywordlessonitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='icon_green',
            field=models.ImageField(blank=True, null=True, upload_to='levels/icons/green/', verbose_name='Зелёный дракон'),
        ),
        migrations.AddField(
            model_name='level',
            name='icon_pink',
            field=models.ImageField(blank=True, null=True, upload_to='levels/icons/pink/', verbose_name='Розовый дракон'),
        ),
        migrations.AlterField(
            model_name='level',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='levels/icons/', verbose_name='Голубой дракон'),
        ),
    ]
