# Generated by Django 6.1 on 2026-09-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_avatar_dragon_color'),
        ('word_learning', '0014_level_icon_green_level_icon_pink_alter_level_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='icon_green',
        ),
        migrations.RemoveField(
            model_name='level',
            name='icon_pink',
        ),
        migrations.AlterField(
            model_name='level',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='levels/icons/', verbose_name='Иконка по умолчанию (fallback)'),
        ),
        migrations.CreateModel(
            name='DragonLevelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='levels/dragons/', verbose_name='Изображение дракончика')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_dragon_images', to='account.avatar', verbose_name='Аватар')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragon_images', to='word_learning.level', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Изображение дракончика уровня',
                'verbose_name_plural': 'Изображения дракончиков уровней',
                'ordering': ['level_id', 'avatar_id'],
                'constraints': [models.UniqueConstraint(fields=('level', 'avatar'), name='unique_level_avatar_dragon')],
            },
        ),
    ]
