name: kids_lang_app
description: Приложение для изучения языков для детей (RU/KZ/EN/CN)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  audioplayers: ^6.1.0
  # Подключим после API-контента:
  # flutter_tts: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/zenvia-icon.webp"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/zenvia-icon.webp"