# Generated by Django 6.1 on 2026-09-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileicon',
            options={'verbose_name': 'Иконка профиля', 'verbose_name_plural': 'Иконки профилей'},
        ),
    ]
