# Generated by Django 6.1 on 2026-09-15 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userlearninglanguage'),
        ('word_learning', '0011_gamesession_question_count_gamequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildLearningLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Изучаемый язык ребёнка',
                'verbose_name_plural': 'Изучаемые языки детей',
            },
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя ребёнка')),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='Опыт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Профиль ребёнка',
                'verbose_name_plural': 'Профили детей',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('active', 'Активна'), ('expired', 'Истекла'), ('cancelled', 'Отменена')], default='pending', max_length=16, verbose_name='Статус')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Автопродление')),
                ('payment_provider', models.CharField(blank=True, max_length=64, verbose_name='Платёжный провайдер')),
                ('external_payment_id', models.CharField(blank=True, max_length=128, verbose_name='ID платежа у провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(default='KZT', max_length=8, verbose_name='Валюта')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Срок, дней')),
                ('max_children', models.PositiveSmallIntegerField(default=1, verbose_name='Максимум профилей детей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='userlearninglanguage',
            name='unique_user_learning_language',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Родитель', 'verbose_name_plural': 'Родители'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='base_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_xp',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='Имя родителя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, unique=True, verbose_name='Технический логин'),
        ),
        migrations.AddField(
            model_name='childlearninglanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.language', verbose_name='Изучаемый язык'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='base_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_profiles', to='word_learning.language', verbose_name='Базовый язык'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_profiles', to='account.avatar', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='childlearninglanguage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_languages', to='account.childprofile', verbose_name='Профиль ребёнка'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='account.tariffplan', verbose_name='Тариф'),
        ),
        migrations.RemoveField(
            model_name='userlearninglanguage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userlearninglanguage',
            name='profile',
        ),
        migrations.AddConstraint(
            model_name='childlearninglanguage',
            constraint=models.UniqueConstraint(fields=('profile', 'language'), name='unique_child_learning_language'),
        ),
        migrations.DeleteModel(
            name='UserLearningLanguage',
        ),
    ]
