# Generated by Django 6.1 on 2026-09-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_childlearninglanguage_childprofile_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parental_pin_hash',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Хеш родительского PIN'),
        ),
    ]
