# Generated by Django 6.1 on 2026-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_parental_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='dragon_color',
            field=models.CharField(choices=[('blue', 'Голубой'), ('green', 'Зелёный'), ('pink', 'Розовый')], default='blue', max_length=16, verbose_name='Цвет дракончика'),
        ),
    ]
