# Generated by Django 6.1 on 2026-09-24 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_avatar_dragon_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название детского сада')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Детский сад',
                'verbose_name_plural': 'Детские сады',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='dragon_color',
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Отключите для скрытых тарифов, доступных только по промокоду.', verbose_name='Показывать в общем списке'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Промокод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Оставьте пустым, если лимита нет.', null=True, verbose_name='Максимальное число использований')),
                ('one_use_per_parent', models.BooleanField(default=True, verbose_name='Одно использование на родителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='account.kindergarten', verbose_name='Детский сад')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_codes', to='account.tariffplan', verbose_name='Скрытый тариф')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['kindergarten__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Использован')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='account.promocode', verbose_name='Промокод')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usage', to='account.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'ordering': ['-used_at'],
            },
        ),
    ]
