# Generated by Django 6.1 on 2026-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_kindergarten_remove_avatar_dragon_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interface_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақша'), ('en', 'English'), ('zh', '中文')], default='ru', max_length=5, verbose_name='Язык интерфейса родителя'),
        ),
    ]
