# Generated by Django 6.1 on 2026-09-08 07:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0002_remove_topic_title_concept_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordprogress',
            name='last_played_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 8, 7, 14, 59, 451023, tzinfo=datetime.timezone.utc), verbose_name='Дата последней игры'),
        ),
        migrations.CreateModel(
            name='LiteraryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Пословица/стих')),
                ('audio', models.FileField(blank=True, null=True, upload_to='content/audios/', verbose_name='Аудио')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/images/', verbose_name='Картинка')),
                ('author', models.CharField(blank=True, max_length=128, null=True, verbose_name='Автор')),
                ('difficulty', models.CharField(choices=[('Easy', 'Легко'), ('Medium', 'Средне'), ('Hard', 'Сложно')], verbose_name='Сложность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Пословица или стих',
                'verbose_name_plural': 'Пословицы или стихи',
            },
        ),
        migrations.CreateModel(
            name='ProfileContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compleated', models.BooleanField(default=False, verbose_name='Изучен ли?')),
                ('listen_count', models.IntegerField(default=0, verbose_name='Кол-во прослушиваний')),
                ('last_opened_at', models.DateTimeField(default=datetime.datetime(2026, 9, 8, 7, 14, 59, 451023, tzinfo=datetime.timezone.utc), verbose_name='Дата последнего открытия')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_learning.literarycontent', verbose_name='Пословица/стих')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс по пословице или стиху',
                'verbose_name_plural': 'Прогресс по пословицам и стихам',
            },
        ),
    ]
