# Generated by Django 6.1 on 2026-09-08 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0003_alter_wordprogress_last_played_at_literarycontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordprogress',
            name='mastery',
            field=models.IntegerField(default=0, verbose_name='Статус знания'),
        ),
        migrations.AlterField(
            model_name='profilecontentprogress',
            name='last_opened_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 8, 7, 24, 51, 153637, tzinfo=datetime.timezone.utc), verbose_name='Дата последнего открытия'),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='last_played_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 8, 7, 24, 51, 153637, tzinfo=datetime.timezone.utc), verbose_name='Дата последней игры'),
        ),
    ]
