# Generated by Django 6.1 on 2026-09-09 06:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0005_achievement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('xp_required', models.PositiveIntegerField(unique=True, verbose_name='Необходимый опыт')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='levels/icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.RenameField(
            model_name='profilecontentprogress',
            old_name='is_compleated',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='achievement',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='word_learning.language', verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='word_learning.topic', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание игры'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало игры'),
        ),
        migrations.AddField(
            model_name='literarycontent',
            name='content_type',
            field=models.CharField(choices=[('poem', 'Стихотворение'), ('proverb', 'Пословица'), ('riddle', 'Загадка'), ('tongue_twister', 'Скороговорка')], default=2008, max_length=32, verbose_name='Тип контента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='literarycontent',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='correct_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во правильных'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('image_choice', 'Выбери картинку'), ('word_choice', 'Выбери слово'), ('audio_choice', 'Прослушай и выбери'), ('matching', 'Найди пару')], max_length=128, verbose_name='Тип игры'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='wrong_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во неправильных'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='Получаемый опыт'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='literarycontent',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Легко'), ('Medium', 'Средне'), ('Hard', 'Сложно')], max_length=16, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='profilecontentprogress',
            name='last_opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего открытия'),
        ),
        migrations.AlterField(
            model_name='profilecontentprogress',
            name='listen_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во прослушиваний'),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Попытки'),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во правильных ответов'),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='last_played_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последней игры'),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='mastery',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Статус знания'),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во неправильных ответов'),
        ),
        migrations.AddConstraint(
            model_name='profilecontentprogress',
            constraint=models.UniqueConstraint(fields=('profile', 'content'), name='unique_profile_content_progress'),
        ),
        migrations.AddConstraint(
            model_name='topictranslate',
            constraint=models.UniqueConstraint(fields=('topic', 'language'), name='unique_topic_language'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('concept', 'language'), name='unique_concept_language'),
        ),
        migrations.AddConstraint(
            model_name='wordprogress',
            constraint=models.UniqueConstraint(fields=('profile', 'concept', 'language'), name='unique_user_concept_language_progress'),
        ),
    ]
