# Generated by Django 6.1 on 2026-09-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learning', '0007_alter_achievement_condition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='xp_reward',
            field=models.PositiveIntegerField(default=0, verbose_name='Получаемый опыт'),
        ),
    ]
